# Generated by Django 2.2.3 on 2019-07-18 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('estc', models.PositiveIntegerField(help_text='ESTC ID number', primary_key=True, serialize=False)),
                ('vid', models.PositiveIntegerField(help_text='Alternate ID number', unique=True)),
                ('title', models.CharField(db_index=True, help_text='Title (as cataloged by ESTC)', max_length=1000)),
                ('publisher', models.CharField(blank=True, help_text='Publisher (as cataloged by ESTC)', max_length=500)),
                ('pdf', models.CharField(blank=True, help_text='relative file path to root directory containing pdfs', max_length=2000, null=True, unique=True)),
            ],
            options={
                'ordering': ['estc'],
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('classname', models.CharField(help_text='A human-readable, unique class identifier', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, help_text='Image notes', max_length=500)),
                ('jpg', models.CharField(help_text='relative file path to root directory containing all images', max_length=2000, unique=True)),
                ('tif', models.CharField(help_text='relative file path to root directory containing all images', max_length=2000, unique=True)),
                ('jpg_md5', models.UUIDField(help_text='md5 hash of the jpg file (as hex digest)')),
                ('tif_md5', models.UUIDField(help_text='md5 hash of the tif file (as hex digest)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(db_index=True, help_text='Order on page, from top to bottom')),
                ('y_min', models.PositiveIntegerField(help_text='Y-axis index for the start of this line on the Page image')),
                ('y_max', models.PositiveIntegerField(help_text='Y-axis index for the end of this line on the Page image')),
            ],
            options={
                'ordering': ['created_by_run', 'page', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(db_index=True, help_text='Sequence of this page in a given book')),
                ('book', models.ForeignKey(help_text='Book to which this spread belongs', on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='pp.Book')),
                ('image', models.ForeignKey(blank=True, help_text='Image depicting this spread', on_delete=django.db.models.deletion.CASCADE, related_name='depicts_spread', to='pp.Image')),
            ],
            options={
                'unique_together': {('book', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='PageRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_path', models.CharField(help_text='Filepath of the script governing this run', max_length=2000)),
                ('script_md5', models.UUIDField(help_text='md5 hash of the script (as hex digest)')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('params', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageruns', to='pp.Book')),
            ],
            options={
                'ordering': ['date_started'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('s', 'single'), ('l', 'left'), ('r', 'right')], help_text='Side of the spread this has been segmented to', max_length=1)),
                ('x_min', models.PositiveIntegerField(help_text='Starting x-axis location of the page on the original spread image')),
                ('x_max', models.PositiveIntegerField(help_text='Ending x-axis location of the page on the original spread image')),
                ('created_by_run', models.ForeignKey(help_text='Which pipeline run created this object instance', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pp.PageRun')),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='depicts_page', to='pp.Image')),
                ('spread', models.ForeignKey(help_text='Spread ID this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pp.Spread')),
            ],
            options={
                'ordering': ['created_by_run', 'spread', 'side'],
                'unique_together': {('created_by_run', 'spread', 'side')},
            },
        ),
        migrations.CreateModel(
            name='LineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_path', models.CharField(help_text='Filepath of the script governing this run', max_length=2000)),
                ('script_md5', models.UUIDField(help_text='md5 hash of the script (as hex digest)')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('params', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineruns', to='pp.Book')),
            ],
            options={
                'ordering': ['date_started'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineGroupRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_path', models.CharField(help_text='Filepath of the script governing this run', max_length=2000)),
                ('script_md5', models.UUIDField(help_text='md5 hash of the script (as hex digest)')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('params', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linegroupruns', to='pp.Book')),
            ],
            options={
                'ordering': ['date_started'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_groups', to='pp.LineGroupRun')),
                ('lines', models.ManyToManyField(related_name='line_groups', to='pp.Line')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_groups', to='pp.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='line',
            name='created_by_run',
            field=models.ForeignKey(help_text='Which pipeline run created this object instance', on_delete=django.db.models.deletion.CASCADE, to='pp.LineRun'),
        ),
        migrations.AddField(
            model_name='line',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='depicts_line', to='pp.Image'),
        ),
        migrations.AddField(
            model_name='line',
            name='page',
            field=models.ForeignKey(help_text='Page ID of this line', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pp.Page'),
        ),
        migrations.CreateModel(
            name='CharacterRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_path', models.CharField(help_text='Filepath of the script governing this run', max_length=2000)),
                ('script_md5', models.UUIDField(help_text='md5 hash of the script (as hex digest)')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('params', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterruns', to='pp.Book')),
            ],
            options={
                'ordering': ['date_started'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together={('created_by_run', 'page', 'sequence')},
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(db_index=True, help_text='Sequence of characters on the line')),
                ('x_min', models.PositiveIntegerField(help_text='X-axis index for the start of this character on the line image')),
                ('x_max', models.PositiveIntegerField(help_text='X-axis index for the end of this character on the line image')),
                ('class_probability', models.FloatField()),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='pp.CharacterClass')),
                ('created_by_run', models.ForeignKey(help_text='Which pipeline run created this object instance', on_delete=django.db.models.deletion.CASCADE, to='pp.CharacterRun')),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='depicts_character', to='pp.Image')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='pp.Line')),
            ],
            options={
                'ordering': ['created_by_run', 'line', 'sequence'],
                'unique_together': {('created_by_run', 'line', 'sequence')},
            },
        ),
    ]
