# Generated by Django 2.2.3 on 2019-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='filepath',
            field=models.CharField(help_text='relative file path to root directory containing all images', max_length=2000, unique=True),
        ),
    ]
