# Generated by Django 2.2.6 on 2019-10-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='pp_publisher',
        ),
    ]
