# Generated by Django 2.2.3 on 2019-07-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.ForeignKey(blank=True, help_text='File object containing original PDF of this book. See the files/ endpoint.', limit_choices_to={'filetype': 'pdf'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_depicted', to='pp.ImageFile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='notes',
            field=models.CharField(blank=True, help_text='Image notes', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='web_file',
            field=models.OneToOneField(blank=True, help_text='The JPG file version of this image, if it exists', limit_choices_to={'filetype': 'jpg'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pp.ImageFile'),
        ),
        migrations.AlterField(
            model_name='line',
            name='page',
            field=models.ForeignKey(help_text='Page ID of this line', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pp.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='spread',
            field=models.ForeignKey(help_text='Spread ID this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pp.Spread'),
        ),
    ]
