# Generated by Django 2.2.3 on 2019-07-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linegroup',
            name='created_by_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linegroups', to='pp.LineGroupRun'),
        ),
        migrations.AlterField(
            model_name='linegroup',
            name='lines',
            field=models.ManyToManyField(related_name='linegroups', to='pp.Line'),
        ),
        migrations.AlterField(
            model_name='linegroup',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linegroups', to='pp.Page'),
        ),
    ]
