# Generated by Django 2.2.3 on 2019-07-18 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='created_by_run',
            field=models.ForeignKey(help_text='Which pipeline run created this object instance', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pp.LineRun'),
        ),
    ]
