# Generated by Django 2.2.3 on 2019-07-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_auto_20190719_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterrun',
            options={'ordering': ['-date_started']},
        ),
        migrations.AlterModelOptions(
            name='linegrouprun',
            options={'ordering': ['-date_started']},
        ),
        migrations.AlterModelOptions(
            name='linerun',
            options={'ordering': ['-date_started']},
        ),
        migrations.AlterModelOptions(
            name='pagerun',
            options={'ordering': ['-date_started']},
        ),
    ]
