# Generated by Django 2.2.6 on 2019-10-05 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_auto_20191005_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_early',
            field=models.DateField(db_index=True, default=datetime.date(1550, 1, 1)),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_late',
            field=models.DateField(db_index=True, default=datetime.date(1800, 12, 12)),
        ),
    ]
