# Generated by Django 2.2.3 on 2019-07-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_auto_20190711_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='web_file',
            field=models.OneToOneField(blank=True, help_text='direct pointer to the path of the JPG version of this image, if it exists', limit_choices_to={'filetype': 'jpg'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pp.ImageFile'),
        ),
    ]
