# Generated by Django 2.2.3 on 2019-07-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0003_auto_20190715_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='primary_image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='depicts_character', to='pp.Image'),
        ),
        migrations.AlterField(
            model_name='spread',
            name='primary_image',
            field=models.ForeignKey(blank=True, help_text='Image depicting this spread', on_delete=django.db.models.deletion.CASCADE, related_name='depicts_spread', to='pp.Image'),
        ),
    ]
