# Generated by Django 2.2.6 on 2019-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0003_auto_20191005_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_probability',
            field=models.FloatField(db_index=True),
        ),
    ]
