# Generated by Django 2.2.3 on 2019-07-20 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_auto_20190719_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='pp.Image'),
        ),
        migrations.AlterField(
            model_name='line',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pp.Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pp.Image'),
        ),
        migrations.AlterField(
            model_name='spread',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='pp.Image'),
        ),
    ]
