# Generated by Django 2.2.3 on 2019-07-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_auto_20190715_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='jpg',
            field=models.CharField(blank=True, help_text='relative file path to root directory containing all images', max_length=2000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='image',
            name='tif',
            field=models.CharField(blank=True, help_text='relative file path to root directory containing all images', max_length=2000, null=True, unique=True),
        ),
    ]
