# Generated by Django 2.2.3 on 2019-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0005_auto_20190715_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='web_file',
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.CharField(blank=True, help_text='relative file path to root directory containing pdfs', max_length=2000, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
