# Generated by Django 2.2.6 on 2019-11-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0005_auto_20191108_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='jpg',
        ),
        migrations.RemoveField(
            model_name='image',
            name='jpg_md5',
        ),
    ]
