# Generated by Django 2.2.3 on 2019-07-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pp", "0005_auto_20190719_2256")]

    operations = [
        migrations.RenameField(model_name="book", old_name="estc", new_name="eebo"),
        migrations.AlterModelOptions(name="book", options={"ordering": ["eebo"]}),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(
                blank=True, help_text="Publisher (as cataloged by EEBO)", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                db_index=True, help_text="Title (as cataloged by EEBO)", max_length=1000
            ),
        ),
    ]
