# Generated by Django 2.2.3 on 2019-07-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0006_auto_20190715_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='jpg',
            field=models.CharField(help_text='relative file path to root directory containing all images', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tif',
            field=models.CharField(help_text='relative file path to root directory containing all images', max_length=2000, unique=True),
        ),
    ]
