# Generated by Django 2.2.4 on 2019-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0006_auto_20190722_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='eebo',
            field=models.PositiveIntegerField(help_text='EEBO ID number', primary_key=True, serialize=False),
        ),
    ]
