# Generated by Django 2.2.4 on 2019-08-24 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pp', '0007_auto_20190823_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterGrouping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(help_text='A descriptive label (will appear in menus etc)', max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, help_text='A description or notes about the grouping', max_length=10000)),
                ('characters', models.ManyToManyField(related_name='charactergroupings', to='pp.Character')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charactergroupings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_by', '-date_created'],
                'abstract': False,
            },
        ),
    ]
