# Generated by Django 2.2.4 on 2019-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0008_charactergrouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactergrouping',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='charactergroupings', to='pp.Character'),
        ),
    ]
