# Generated by Django 2.2.4 on 2019-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0009_auto_20190919_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='characterrun',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='line',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='linegroup',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='linegrouprun',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='linerun',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='page',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='pagerun',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='spread',
            name='label',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
    ]
