# Generated by Django 2.2.4 on 2019-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0010_auto_20190922_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bad',
            field=models.BooleanField(db_index=True, help_text='Has this character been marked as bad by human reviewers?', null=True),
        ),
    ]
