# Generated by Django 2.2.7 on 2019-11-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0010_auto_20191111_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='data',
        ),
        migrations.RemoveField(
            model_name='line',
            name='image',
        ),
    ]
