# Generated by Django 2.2.5 on 2019-09-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0011_character_bad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='bad',
        ),
        migrations.AddField(
            model_name='character',
            name='human_character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_assigned_to', to='pp.CharacterClass'),
        ),
    ]
