# Generated by Django 2.2.5 on 2019-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0012_auto_20190926_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.CharField(help_text='relative file path to root directory containing pdfs', max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='Publisher (as cataloged by EEBO)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, help_text='Title (as cataloged by EEBO)', max_length=2000),
        ),
    ]
