# Generated by Django 2.2.6 on 2019-10-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_auto_20191013_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pq_year_early',
            field=models.PositiveIntegerField(db_index=True, editable=False, help_text='Proquest early year', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pq_year_late',
            field=models.PositiveIntegerField(db_index=True, editable=False, help_text='Proquest late year', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tx_year_early',
            field=models.PositiveIntegerField(db_index=True, editable=False, help_text='Texas A&M early year', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tx_year_late',
            field=models.PositiveIntegerField(db_index=True, editable=False, help_text='Texas A&M late year', null=True),
        ),
    ]
