# Generated by Django 2.2.6 on 2019-10-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0003_auto_20191021_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pq_year_verbatim',
            field=models.CharField(blank=True, editable=False, help_text='Date string from EEBO, may contain non-numeric values', max_length=2000),
        ),
    ]
