# Generated by Django 2.2.6 on 2019-11-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_book_pq_year_verbatim'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exposure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
