# Generated by Django 2.2.7 on 2019-12-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0011_auto_20191115_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='zipfile',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
