# Generated by Django 2.2.7 on 2019-12-25 22:40

from django.db import migrations, models


def spread_add_image(apps, schema_editor):
    Spread = apps.get_model("pp", "Spread")
    for spread in Spread.objects.all():
        spread.tif = spread.image.tif
        spread.tif_md5 = spread.image.tif_md5
        spread.save()


def page_add_image(apps, schema_editor):
    Page = apps.get_model("pp", "Page")
    for page in Page.objects.all():
        page.tif = page.image.tif
        page.tif_md5 = page.image.tif_md5
        page.save()


class Migration(migrations.Migration):

    dependencies = [("pp", "0012_book_zipfile")]

    operations = [
        migrations.AddField(
            model_name="page",
            name="tif",
            field=models.CharField(
                blank=True,
                help_text="relative file path to root directory containing all images",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="tif_md5",
            field=models.UUIDField(
                help_text="md5 hash of the tif file (as hex digest)", null=True
            ),
        ),
        migrations.RunPython(page_add_image),
        migrations.AddField(
            model_name="spread",
            name="tif",
            field=models.CharField(
                blank=True,
                help_text="relative file path to root directory containing all images",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="spread",
            name="tif_md5",
            field=models.UUIDField(
                help_text="md5 hash of the tif file (as hex digest)", null=True
            ),
        ),
        migrations.RunPython(spread_add_image),
        migrations.RemoveField(model_name="page", name="image"),
        migrations.RemoveField(model_name="spread", name="image"),
        migrations.DeleteModel(name="Image"),
    ]
