# Generated by Django 2.2.7 on 2020-01-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0013_auto_20191225_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ignored',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
