# Generated by Django 3.0.2 on 2020-01-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0014_auto_20191231_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_eebo_book',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='eebo',
            field=models.PositiveIntegerField(db_index=True, help_text='EEBO ID number', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='estc',
            field=models.CharField(blank=True, db_index=True, help_text='English Short Title Catalogue Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='tcp',
            field=models.CharField(blank=True, db_index=True, help_text='TCP ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='vid',
            field=models.PositiveIntegerField(db_index=True, help_text='Proquest ID number', null=True),
        ),
    ]
