# Generated by Django 3.0.2 on 2020-01-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0015_auto_20200107_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pq_title',
            field=models.CharField(db_index=True, help_text='Title (as cataloged by EEBO)', max_length=2000),
        ),
    ]
