# Generated by Django 3.0.2 on 2020-02-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0016_auto_20200107_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='prefix',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
