# Generated by Django 3.0.3 on 2020-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0017_book_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='group',
            field=models.CharField(choices=[('cl', 'Lowercase'), ('cu', 'Uppercase'), ('pu', 'Punctuation')], default='cl', max_length=2),
        ),
    ]
