# Generated by Django 3.0.3 on 2020-03-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0018_characterclass_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterclass',
            options={'ordering': ['group', 'classname']},
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='group',
            field=models.CharField(choices=[('cl', 'Lowercase'), ('cu', 'Uppercase'), ('pu', 'Punctuation')], db_index=True, default='cl', max_length=2),
        ),
    ]
