# Generated by Django 3.0.3 on 2020-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0019_auto_20200303_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='group',
            field=models.CharField(choices=[('cl', 'Lowercase'), ('cu', 'Uppercase'), ('nu', 'Number'), ('pu', 'Punctuation')], db_index=True, default='cl', max_length=2),
        ),
    ]
