# Generated by Django 3.0.4 on 2020-05-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Run the page counts update using direct SQL statements
    """

    dependencies = [("pp", "0020_auto_20200303_1231")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="n_spreads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunSQL(
            "CREATE TEMP TABLE spreadcounts AS SELECT pp_book.id AS id, COUNT(pp_spread.id) AS n FROM pp_book LEFT JOIN pp_spread ON(pp_book.id=pp_spread.book_id) GROUP BY pp_book.id; UPDATE pp_book SET n_spreads=spreadcounts.n FROM spreadcounts WHERE pp_book.id=spreadcounts.id;"
        ),
    ]
