# Generated by Django 3.0.4 on 2020-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0021_book_n_spreads'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
