# Generated by Django 3.0.4 on 2020-06-03 19:28

from django.db import migrations, models


def pages_add_sequence(apps, schema_editor):
    Page = apps.get_model("pp", "Page")
    PageRun = apps.get_model("pp", "PageRun")
    paged_books = PageRun.objects.exclude(pages__isnull=True).all()
    for pb in paged_books:
        all_pages = pb.pages.all()
        for i, page in enumerate(all_pages):
            page.sequence = i
            page.save()


class Migration(migrations.Migration):

    dependencies = [("pp", "0022_page_sequence")]

    operations = [migrations.RunPython(pages_add_sequence)]
