# Generated by Django 3.0.4 on 2020-06-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0023_auto_20200603_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['created_by_run', 'sequence']},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('created_by_run', 'sequence')},
        ),
        migrations.RemoveField(
            model_name='page',
            name='spread',
        ),
    ]
