# Generated by Django 3.0.4 on 2020-06-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0024_auto_20200603_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linegrouprun',
            name='book',
        ),
        migrations.DeleteModel(
            name='LineGroup',
        ),
        migrations.DeleteModel(
            name='LineGroupRun',
        ),
    ]
