# Generated by Django 3.0.4 on 2020-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0026_auto_20200629_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='h',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='rot1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='rot2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='w',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
