# Generated by Django 3.0.4 on 2020-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0027_auto_20200916_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='label',
            field=models.CharField(default='', help_text='Human-readable label', max_length=5),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='classname',
            field=models.CharField(help_text='Unique Ocular identifier', max_length=50, primary_key=True, serialize=False),
        ),
    ]
