# Generated by Django 3.0.4 on 2020-09-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0028_auto_20200916_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='label',
            field=models.CharField(default='', help_text='Human-readable label', max_length=15),
        ),
    ]
