# Generated by Django 3.0.4 on 2020-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0031_auto_20200923_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pq_author',
            field=models.CharField(blank=True, help_text='Author (as cataloged by EEBO)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='pq_publisher',
            field=models.CharField(blank=True, help_text='Publisher (as cataloged by EEBO)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='pq_year_verbatim',
            field=models.CharField(blank=True, help_text='Date string from EEBO, may contain non-numeric values', max_length=2000),
        ),
    ]
