# Generated by Django 3.0.4 on 2020-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0032_auto_20200924_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pp_author',
            field=models.CharField(blank=True, help_text='Author as asserted by P&P team', max_length=2000),
        ),
    ]
