# Generated by Django 3.0.4 on 2020-09-24 15:09

from django.db import migrations
from django.db.models import F


class Migration(migrations.Migration):
    def copy_author(apps, schema_editor):
        # Copy existing pq_author data to pp_author field
        Book = apps.get_model("pp", "Book")
        Book.objects.all().update(pp_author=F("pq_author"))

    dependencies = [
        ("pp", "0033_book_pp_author"),
    ]

    operations = [migrations.RunPython(copy_author)]
