# Generated by Django 3.0.4 on 2020-09-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0034_auto_20200924_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pq_url',
            field=models.URLField(blank=True, help_text='ProQuest URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='pq_year_early',
            field=models.PositiveIntegerField(db_index=True, help_text='Proquest early year', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pq_year_late',
            field=models.PositiveIntegerField(db_index=True, help_text='Proquest late year', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tx_year_early',
            field=models.PositiveIntegerField(db_index=True, help_text='Texas A&M early year', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tx_year_late',
            field=models.PositiveIntegerField(db_index=True, help_text='Texas A&M late year', null=True),
        ),
    ]
