# Generated by Django 3.1.3 on 2020-11-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0037_auto_20200926_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='repository',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True),
        ),
    ]
