# Generated by Django 3.1.3 on 2021-01-04 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0040_book_colloq_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_early',
            field=models.DateField(db_index=True, default=datetime.date(1550, 1, 1), help_text='The earliest date this book may have been printed'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_late',
            field=models.DateField(db_index=True, default=datetime.date(1800, 12, 12), help_text='The latest date this book may have been printed'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ignored',
            field=models.BooleanField(db_index=True, default=False, help_text="This book has been marked as ignored by a user, and won't show up in search results"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_eebo_book',
            field=models.BooleanField(db_index=True, default=False, help_text='Are these book images from ProQuest EEBO?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='n_spreads',
            field=models.PositiveIntegerField(default=0, help_text='Number of spread images for this book. Only used for EEBO images.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='prefix',
            field=models.CharField(blank=True, help_text='Prefix to most Bridges files for this book, e.g. `thodgkin` for thodgkin_xxxxx_yyyyy_00height_caesarsF.txt', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='repository',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Name of the library/collection where these book images came from, e.g. 'British Library'", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='starred',
            field=models.BooleanField(db_index=True, default=False, help_text='This book has been maunally starred by a  user'),
        ),
        migrations.AlterField(
            model_name='book',
            name='zipfile',
            field=models.CharField(blank=True, help_text='Location of ZIP file of images on Bridges, for EEBO books only', max_length=1000),
        ),
    ]
