# Generated by Django 3.2.3 on 2021-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0041_auto_20210104_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='eebo',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='EEBO ID number', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='vid',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Proquest ID number', null=True),
        ),
    ]
