# Generated by Django 3.2.12 on 2022-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0043_auto_20220123_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='damage_score',
            field=models.FloatField(blank=True, db_index=True, help_text='Machine-generated score for the level of damage of the character.', null=True),
        ),
    ]
