# Generated by Django 3.2.13 on 2022-05-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0044_character_damage_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['created_by_run', 'line']},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='spread',
            unique_together=set(),
        ),
    ]
