# Generated by Django 3.2.13 on 2022-06-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0045_auto_20220503_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['created_by_run', 'line', 'sequence']},
        ),
    ]
