# Generated by Django 3.2.13 on 2022-05-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0045_auto_20220503_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['created_by_run', 'line', 'sequence']},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('created_by_run', 'line', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together={('created_by_run', 'page', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('created_by_run', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='spread',
            unique_together={('book', 'sequence')},
        ),
    ]
