# Generated by Django 3.2.14 on 2022-12-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0047_remove_character_breakage_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(help_text='Book corresponding to this character match', on_delete=django.db.models.deletion.CASCADE, related_name='book_character_match', to='pp.book')),
                ('match', models.ForeignKey(help_text='Match character corresponding to this character query', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_character', to='pp.character')),
                ('query', models.ForeignKey(help_text='Query character corresponding to this character match', on_delete=django.db.models.deletion.CASCADE, related_name='query_character', to='pp.character')),
            ],
        ),
    ]
